require('core.plugin_config.cmp')
require('core.plugin_config.lsp')
require('core.plugin_config.nvim_treesitter')
require('core.plugin_config.lualine')
require('core.plugin_config.ibl')
require('core.plugin_config.presence')
require('core.plugin_config.gitsigns')
require('core.plugin_config.mason')
